import initScrollSuave from './js-modules/scroll-suave.js';
import initAnimacaoScroll from './js-modules/animacao-scroll.js';
import initAccordion from './js-modules/accordion.js';
import initTabNav from './js-modules/tabnav.js';
import initModal from './js-modules/modal.js';
import initTooltip from './js-modules/tooltip.js';
import initDropdownMenu from './js-modules/dropdown-menu.js';
import initMenuMobile from './js-modules/menu-mobile.js';
import initFuncionamento from './js-modules/funcionamento.js';
import initFetchAnimais from './js-modules/fetch-animais.js';
import initFetchBitcoin from './js-modules/fetch-bitcoin.js';

initTabNav();
initScrollSuave();
initAnimacaoScroll();
initAccordion();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
initFetchBitcoin();
